### ISSUE TITLE
silence.py in reverse? Remove silent parts from video

### ISSUE THREAD

**Issue by kingsofcoms** [antiboredom/videogrep#54]
How to remove silent parts for super-fast commentary with added padding option before and after a dialogue.

**Comment by opensourcegrappler** [comment]
You can do this like so:
`videogrep --input "my_movie.avi" --search '.'`

Since the default search type is regex by putting '.' as the search term it will match to any character. If you didn't realise in the .srt file that contains the subtitles for your video each subtitle has a start and end time. By supercutting together all subtitles the time in between them is removed, the silence is removed.
